###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "fullname" . }}"
spec:
  replicas: {{ .Values.service.replicas }}
  template:
    metadata:
      name: {{ template "fullname" . }} 
      labels:
        app: {{ template "fullname" . }} 
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
      - name: {{ template "fullname" . }} 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}        
        ports:
        - containerPort: {{ .Values.service.adminConsolePort }}
          name: adminconsole
        - containerPort: {{ .Values.service.portalPort }}
          name: portal
        env:
        -
         name : LICENSE
         value : {{ .Values.license }}
        -
         name : NODENAME
         value : "IIB_NODE"
        -
         name : SERVERNAME
         value : "IIB_SERVER" 
        readinessProbe:
          httpGet:
            path: /wps/portal
            port: 10039
          initialDelaySeconds: 90
          timeoutSeconds: 10
        resources:
          limits:
{{ toYaml .Values.resources.limits | indent 14 }}
          requests:
{{ toYaml .Values.resources.requests | indent 14 }}
