###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "fullname" . }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.adminConsolePort }}
    targetPort: {{ .Values.service.adminConsolePort }}
    protocol: TCP
    name: adminconsole
  - port: {{ .Values.service.portalPort }}
    targetPort: {{ .Values.service.portalPort }}
    protocol: TCP
    name: portal
  selector:
    app: {{ template "fullname" . }}
